inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/release/0.29-stable/.rubocop.yml

AllCops:
  Exclude:
    - "spec/decidim_dummy_app*/**/*"
    - "development_app/**/*"
    - "node_modules/**/*"

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/i18n_spec.rb'
