inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - "spec/decidim_dummy_app*/**/*"
    - "development_app/**/*"
    - "node_modules/**/*"

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/i18n_spec.rb'
