name: "[CI] Lint"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

env:
  RUBY_VERSION: 3.1.6
  NODE_VERSION: 18.17.1

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
        name: Install JS deps

      - run: npm run lint
        name: Lint JS files

      - run: npm run stylelint
        name: Lint SCSS files

      - name: Remove old bundler cache
        run: rm -rf ~/.bundle ~/.gem /vendor/bundle

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erblint app/**/*.erb
        name: Lint ERB files
