name: "[CI] Lint"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 2.7.6

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle exec rubocop -P
        name: Lint Ruby files
